
# JVM
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX — keep enabled (required)
android.useAndroidX=true
android.enableJetifier=false
# Non-transitive R classes (faster builds)
android.nonTransitiveRClass=true

# Gradle performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
org.gradle.configuration-cache=true
