# Production Profile

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

app.otp.dev-mode-enabled=false
app.firebase.enabled=true

logging.level.com.mobilewallet=INFO
logging.level.org.springframework.security=INFO

server.error.include-stacktrace=never

management.endpoints.web.exposure.include=health,info